# Maya DevKit Configuration
# Official Autodesk Maya DevKit URLs from https://aps.autodesk.com/developer/overview/maya
# These DevKits include headers, libraries, and documentation for Maya plugin development

[devkit]
# Base URL for Autodesk ADN Transfer
base_url = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya"

# Supported Maya versions
supported_versions = ["2022", "2023", "2024", "2025", "2026"]

# Platform mappings
[devkit.platforms]
windows = "Windows"
linux = "Linux" 
macos = "Mac"

# DevKit URLs for each version and platform
[devkit.urls]

# Maya 2022
[devkit.urls."2022"]
windows = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2022/Autodesk_Maya_2022_DEVKIT_Windows.zip"
linux = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2022/Autodesk_Maya_2022_DEVKIT_Linux.tgz"
macos = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2022/Autodesk_Maya_2022_DEVKIT_Mac.dmg"

# Maya 2023
[devkit.urls."2023"]
windows = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2023/Autodesk_Maya_2023_DEVKIT_Windows.zip"
linux = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2023/Autodesk_Maya_2023_DEVKIT_Linux.tgz"
macos = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2023/Autodesk_Maya_2023_DEVKIT_Mac.dmg"

# Maya 2024
[devkit.urls."2024"]
windows = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2024/Autodesk_Maya_2024_DEVKIT_Windows.zip"
linux = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2024/Autodesk_Maya_2024_DEVKIT_Linux.tgz"
macos = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2024/Autodesk_Maya_2024_DEVKIT_Mac.dmg"

# Maya 2025
[devkit.urls."2025"]
windows = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2025/Autodesk_Maya_2025_DEVKIT_Windows.zip"
linux = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2025/Autodesk_Maya_2025_DEVKIT_Linux.tgz"
macos = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2025/Autodesk_Maya_2025_DEVKIT_Mac.dmg"

# Maya 2026
[devkit.urls."2026"]
windows = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2026/Autodesk_Maya_2026_DEVKIT_Windows.zip"
linux = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2026/Autodesk_Maya_2026_DEVKIT_Linux.tgz"
macos = "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2026/Autodesk_Maya_2026_DEVKIT_Mac.dmg"

# File extraction patterns for different archive types
[devkit.extraction]
zip_pattern = "*devkit*"
tgz_pattern = "*devkit*"
dmg_pattern = "*devkit*"

# Platform-specific DevKit directory structure
[devkit.structure]
windows = "devkitBase"
linux = "devkitBase"
macos = "devkitBase"
