param(
    [string]$MayaVersion = "2024",
    [string]$PackageRoot = "dist\modules",
    [string]$ScenePath = "tests\virus\uifiguration.ma",
    [string]$Mayapy = "",
    [switch]$UnsafeAllowScriptNodes,
    [switch]$CleanEnvironment
)

$ErrorActionPreference = "Stop"

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")

function Resolve-InputPath([string]$Path) {
    if ([System.IO.Path]::IsPathRooted($Path)) {
        return Resolve-Path -LiteralPath $Path
    }
    return Resolve-Path -LiteralPath (Join-Path $Root $Path)
}

if ([string]::IsNullOrWhiteSpace($Mayapy)) {
    $Candidates = @(
        "C:\Program Files\Autodesk\Maya$MayaVersion\bin\mayapy.exe",
        "/usr/autodesk/maya$MayaVersion/bin/mayapy",
        "/Applications/Autodesk/maya$MayaVersion/Maya.app/Contents/bin/mayapy"
    )
    $Mayapy = $Candidates | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
}

if ([string]::IsNullOrWhiteSpace($Mayapy) -or -not (Test-Path -LiteralPath $Mayapy)) {
    throw "mayapy not found. Pass -Mayapy or run inside a Maya Docker image with mayapy available."
}

$PackageRootPath = Resolve-InputPath $PackageRoot
$Package = Get-ChildItem -LiteralPath $PackageRootPath -Directory -Filter "UmbrellaMayaPlugin-*-maya$MayaVersion-*" |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

if (-not $Package) {
    throw "No Maya module package for Maya $MayaVersion under $PackageRootPath. Run 'vx just package $MayaVersion' first."
}

$PluginExtension = if ($IsWindows -or $env:OS -eq "Windows_NT") { ".mll" } elseif ($IsMacOS) { ".bundle" } else { ".so" }
$PluginPath = Join-Path $Package.FullName "UmbrellaMayaPlugin\plug-ins\umbrella_maya$PluginExtension"
if (-not (Test-Path -LiteralPath $PluginPath)) {
    throw "Plugin binary missing: $PluginPath"
}

$ResolvedScenePath = Resolve-InputPath $ScenePath
$ScriptDirectory = Join-Path ([System.IO.Path]::GetTempPath()) ("umbrella-maya-smoke-" + [System.Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $ScriptDirectory | Out-Null
$TempScript = Join-Path $ScriptDirectory "smoke.py"
$ExecuteScriptNodes = if ($UnsafeAllowScriptNodes) { "True" } else { "False" }

Set-Content -Path $TempScript -Encoding UTF8 -Value @"
import maya.standalone
maya.standalone.initialize(name="umbrella_maya_smoke")

from maya import cmds

plugin_path = r"$PluginPath"
scene_path = r"$ResolvedScenePath"

cmds.loadPlugin(plugin_path)
assert cmds.pluginInfo(plugin_path, query=True, loaded=True)
cmds.umbrellaInfo()
cmds.umbrellaEnable()
cmds.file(scene_path, open=True, force=True, ignoreVersion=True, executeScriptNodes=$ExecuteScriptNodes, prompt=False)
cmds.umbrellaScanScene()
cmds.umbrellaDisable()
maya.standalone.uninitialize()
print("[ok] Maya standalone smoke completed")
"@

try {
    $SavedEnvironment = @{}
    $IsolatedAppDirectory = $null
    if ($CleanEnvironment) {
        foreach ($Name in @("PATH", "PYTHONPATH", "PYTHONHOME", "PYTHONNOUSERSITE", "MAYA_LOCATION", "MAYA_APP_DIR", "MAYA_MODULE_PATH", "MAYA_PLUG_IN_PATH", "MAYA_SCRIPT_PATH")) {
            $SavedEnvironment[$Name] = [Environment]::GetEnvironmentVariable($Name, "Process")
            [Environment]::SetEnvironmentVariable($Name, $null, "Process")
        }
        $IsolatedAppDirectory = Join-Path ([System.IO.Path]::GetTempPath()) ("umbrella-maya-profile-" + [System.Guid]::NewGuid().ToString("N"))
        New-Item -ItemType Directory -Path $IsolatedAppDirectory | Out-Null
        $env:MAYA_APP_DIR = $IsolatedAppDirectory
        $env:MAYA_MODULE_PATH = $Package.FullName
        $env:MAYA_LOCATION = Split-Path -Parent (Split-Path -Parent $Mayapy)
        $env:PYTHONNOUSERSITE = "1"
        $env:PATH = Split-Path -Parent $Mayapy
        if ($IsWindows -or $env:OS -eq "Windows_NT") {
            $env:PATH += ";" + (Join-Path $env:SystemRoot "System32")
        } else {
            $env:PATH += ":/usr/bin:/bin"
        }
    }
    & $Mayapy $TempScript
    if ($LASTEXITCODE -ne 0) {
        throw "mayapy exited with code $LASTEXITCODE"
    }
}
finally {
    foreach ($Name in $SavedEnvironment.Keys) {
        [Environment]::SetEnvironmentVariable($Name, $SavedEnvironment[$Name], "Process")
    }
    if ($IsolatedAppDirectory) {
        # This directory was generated by this invocation under the verified temp root.
        $ResolvedAppDirectory = [System.IO.Path]::GetFullPath($IsolatedAppDirectory)
        $ResolvedTempRoot = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath())
        if ($ResolvedAppDirectory.StartsWith($ResolvedTempRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
            Remove-Item -LiteralPath $ResolvedAppDirectory -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
    $ResolvedScriptDirectory = [System.IO.Path]::GetFullPath($ScriptDirectory)
    $ResolvedTempRoot = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath())
    if ($ResolvedScriptDirectory.StartsWith($ResolvedTempRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
        Remove-Item -LiteralPath $ResolvedScriptDirectory -Recurse -Force -ErrorAction SilentlyContinue
    }
}
